### ISSUE TITLE
AttributeError: 'Annotation' object has no attribute 'diameter'

### ISSUE THREAD

**Issue by himalayajung** [pylidc/pylidc#11]
Received the error below while running the example code

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-3353edcc7695> in <module>()
     17 
     18 ann = q.first()
---> 19 print("%.2f, %.2f, %.2f" % (ann.diameter, ann.surface_area, ann.volume))
     20 # => 17.98, 1221.40, 1033.70

AttributeError: 'Annotation' object has no attribute 'diameter'

**Comment by notmatthancock** [comment]
The latest version is now on pip, so you should be able to just run `pip install --upgrade pylidc`. The documentation has been migrated to https://pylidc.github.io and the section that you mentioned  in particular can be found [here](https://pylidc.github.io/tuts/annotation.html#contour-derived-data).

**Comment by himalayajung** [comment]
Thanks :)
