### ISSUE TITLE
Annotation should not include the XML contour points

### ISSUE THREAD

**Issue by fedorov** [pylidc/pylidc#15]
Reading the [annotated XML file](https://wiki.cancerimagingarchive.net/download/attachments/3539039/annotated_xml_file_Mar%202010.rtf?version=1&modificationDate=1319224566198&api=v2) document from the [LIDC-IDRI collection page](https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI), it says the following:

> <roi> signifies beginning of region of interest description roi is a boundary describing either:
>		(a) a single voxel for nodules < 3 mm
>		(b) a complete contour of the nodule that describes the first voxel just outside the nodule. 

I am hopefully missing something, but I cannot find the place in the code where the fact that the XML-defined contour is **outside** the nodule is accounted for. It looks like in pylidc the points of the contour are treated as those that are inside the nodule.

Would be great if it could be confirmed whether the contour points are not considered part of the nodule.

**Comment by fedorov** [comment]
My further experiments seem to confirm my suspicion.

I first exported the mask using the `Annotation.boolean_mask()` call, and pasted it into the volume of the scan, and stored in NRRD format (also stored the scan as NRRD, since the pylidc annotation is not expected to line up with the CT loaded from DICOM), so that I can visualize it outside pylidc:

```python
pid = 'LIDC-IDRI-0011'
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == pid).first()
ann = pl.query(pl.Annotation).filter(pl.Scan.patient_id == pid).first()

vol = scan.to_volume()
mask_full = numpy.zeros(vol.shape)
mask = ann.boolean_mask()
bbox=ann.bbox()
mask_full[bbox[0].start:bbox[0].stop,bbox[1].start:bbox[1].stop,bbox[2].start:bbox[2].stop] = mask

import itk
mi = itk.GetImageFromArray(mask_full.astype(numpy.int16))
imageType = itk.Image[itk.SS, 3]
writerType = itk.ImageFileWriter[imageType]
writer = writerType.New()
writer.SetFileName('/Users/fedorov/Downloads/test3-label.nrrd')
writer.SetInput(mi)
writer.Update()
```

I then took that same mask, and toggled the contour points to have a different value:
```python
for c in ann.contours_matrix:
    mask_full[c[0],c[1],c[2]] = 2
    
mi = itk.GetImageFromArray(mask_full.astype(numpy.int16))
writer.SetFileName('/Users/fedorov/Downloads/test3-noc-label.nrrd')
writer.SetInput(mi)
writer.Update()
```

Next I used [3D Slicer](https://www.slicer.org/) to overlay the `test3-label.nrrd` and `test3-noc-label.nrrd` over the CT volume, and the result seems to confirm that (some of) the contour points are indeed included in the segmentation mask, while, according to the documentation of the collection, they should not be included. In the screencapture below, yellow pixels should correspond to the contour pixels (in the left panel) from `test3-noc-label.nrrd`, and the green pixels in the right panel are from `test3-label.nrrd`. Crosshairs show the same spatial position between the two images. Hopefully it is clear from this demo that *some* contour pixels (something to do with the contour fill approach?) are included in the nodule segmentation.

![jul-26-2018 15-45-32](https://user-images.githubusercontent.com/313942/43284849-1e9ff96e-90eb-11e8-92bb-39e4e315be1d.gif)

**Comment by fedorov** [comment]
For the sake of completeness, I attach the zip file with the complete dataset to reproduce the issue. All you need to do is to download the nightly binary of 3D Slicer for your platform from [here](https://download.slicer.org/), unzip the [pylidc-contour-points.zip](https://github.com/pylidc/pylidc/files/2233396/pylidc-contour-points.zip) file, and open the .mrml file included therein in 3D Slicer application (or just drag-and-drop it into the application window).

**Comment by notmatthancock** [comment]
Nice catch.

As an aside, the `pad` argument will limit not create zeros beyond the volume border. So, if you want the mask placed in the full volume like you've done, you can just do `ann.boolean_mask( some large number )`

**Comment by fedorov** [comment]
> the `pad` argument will limit not create zeros beyond the volume border

Thanks, this is really helpful!
