### ISSUE TITLE
Is filtering supposed to work for querying Annotations?

### ISSUE THREAD

**Issue by fedorov** [pylidc/pylidc#17]
I am confused about the behavior of the query below. Should it filter by patient ID, or not?

![image](https://user-images.githubusercontent.com/313942/43346419-065d8676-91bf-11e8-9180-bdc98b9f1918.png)

**Comment by notmatthancock** [comment]
Scans and Annotation objects are stored in different tables, and so to do this type of query, you need a `join` clause. [See here](https://pylidc.github.io/tuts/advanced-queries.html#query-multiple-model-parameters-with-a-join).

**Comment by notmatthancock** [comment]
Also, to get counts from a query, you can just issue a `count` on the query, e.g.:
```
print pl.query(pl.Annotation).join(pl.Scan)\
        .filter(pl.Scan.patient_id == 'LIDC-IDRI-0011').count()
# 23
```
Alternatively, you can accomplish this same result by:
```
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == 'LIDC-IDRI-0011').first()
print len(scan.annotations)
# 23
```

**Comment by fedorov** [comment]
Thank you! Sorry for the confusion.

**Comment by notmatthancock** [comment]
No problem. FYI, `pylidc` is implemented with `sqlalchemy`, which is where the `filter`, `count`, `join`, etc ... functions come from. `sqlalchemy` has nice documentation if you want to dive deeper into more complex query capabilities.
