### ISSUE TITLE
Can't import marching_cubes with skimage > 13.1

### ISSUE THREAD

**Issue by notmatthancock** [pylidc/pylidc#20]
In scitkit image versions 14 and above, the function `marching_cubes` does not exist. Either `marching_cubes_classic` or `marching_cubes_lewiner` must be called explicitly.

**Comment by fedorov** [comment]
Which of the two are you planning to use?

**Comment by notmatthancock** [comment]
Looking at the source in 13.1, the `marching_cubes` is just a wrapper for `marching_cubes_lewiner`.
