### ISSUE TITLE
Tested on Windows 8

### ISSUE THREAD

**Issue by markloyman** [pylidc/pylidc#6]
I just wanted to update that I've successfully used pylidc on **Window 8** with **python 3.5**.

The analogous location for .pylidcrc is `C:\Users\[User]\.pylidcrc`. There is a minor issue with windows not allowing to creating a file with an empty filename (starting with a dot). The simple workaround is to add another dot in the end of the filename: `.pylidcrc.`.

**Comment by notmatthancock** [comment]
glad to hear it (mostly) works on win 8.

You're saying that if the the file is named `.pylidcrc.`, then the file is still read (despite the fact that the code is looking for `.pylidcrc`)? Would it preferable on windows to look for the file, `pylidc.conf`, or something like that?

**Comment by markloyman** [comment]
When you name a file `.pylidcrc.`, it gets saved as `.pylidcrc`. 
Yes, something like `pylidc.conf` would be more strightforward.

**Comment by notmatthancock** [comment]
Ok thanks; it should look for `pylidc.conf` on Windows now, and the README is updated.
